import React, { ReactNode } from 'react';

const AvisoDePrivacidad = () => {
  const Subtitle = ({ children }: { children: ReactNode }) => {
    return (
      <h2 className="text-xl font-bold mt-8 mb-2">{children}</h2>
    );
  };

  const Paragraph = ({ children }: { children: ReactNode }) => {
    return (
      <p className="mb-3">{children}</p>
    );
  };

  return (
    <div className="container mx-auto p-4">
      <h1 className="text-3xl font-bold mb-4 text-red-500">Aviso de privacidad</h1>
      <Paragraph>El presente documento constituye el Aviso de Privacidad para efectos de lo dispuesto en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (la “LFPDP”) y las disposiciones que emanan de ella o se relacionan con la misma. Este Aviso de Privacidad aplica a la información personal recopilada sobre el titular por LEE & MILLER, S.C. (en lo sucesivo referido como “RADIUS”) con domicilio en Av. Junco de La Vega No. Ext. 108-B, Col. Roma, Monterrey, Nuevo León, C.P. 64700 en su carácter de Responsable. El presente Aviso de Privacidad tiene los siguientes términos y condiciones:</Paragraph>
      
      <Subtitle>1. TÉRMINOS DEFINIDOS.</Subtitle>
      <Paragraph>Para los efectos de este Aviso de Privacidad, los siguientes términos tendrán los siguientes significados, en el entendido de que salvo que en el presente Aviso de Privacidad se definan de otra forma, los términos que se utilicen en este Aviso de Privacidad y que no estén definidos en el mismo tendrán el significado que se les atribuye en la LFPDP:</Paragraph>
      <Paragraph><strong>{"Datos Personales"}</strong> Cualquier información concerniente a una persona física identificada o identificable.</Paragraph>
      <Paragraph><strong>{"Derechos ARCO"}</strong> Significa los derechos de acceso, rectificación, cancelación y, oposición que de conformidad con lo establecido por la LFPDP y sujeto a las excepciones establecidas en la misma y en este Aviso de Privacidad, cada Titular tiene, en relación con los Datos Personales recabados por {"RADIUS"} y/o sus Encargados, y que se describen a continuación:</Paragraph>
      <Paragraph><strong>{"Derecho de Acceso"}</strong> Es el derecho que tiene el Titular a conocer sobre los Datos Personales relacionados a su persona que obren en poder de {"RADIUS"} o de sus Encargados, asimismo a quién le han sido compartidos y con qué finalidad. Descarga la solicitud de Derecho de Acceso.</Paragraph>
      <Paragraph><strong>{"Derecho a la Rectificación"}</strong> Cada Titular tiene derecho a que sus Datos Personales sean rectificados cuando éstos sean inexactos o incompletos.</Paragraph>
      <Paragraph><strong>{"Derecho de Cancelación"}</strong> Cada Titular tiene derecho a solicitar en cualquier momento que se supriman sus Datos Personales, lo cual sucederá una vez que transcurra el periodo de bloqueo. El bloqueo implica la identificación y conservación de los Datos Personales, una vez que se cumpla la finalidad para la cual fueron recabados, y tiene como propósito determinar las posibles responsabilidades en relación con su tratamiento, hasta el plazo de prescripción legal o contractual de éstas. Durante dicho periodo, sus Datos Personales no serán objeto de tratamiento y transcurrido éste, se procederá con su cancelación en la base de datos o archivo correspondiente. Una vez cancelado el dato correspondiente, {"RADIUS"} le dará al Titular el aviso correspondiente. En caso de que los Datos Personales hubiesen sido transmitidos con anterioridad a la fecha de rectificación o cancelación y sigan siendo tratados por terceros, {"RADIUS"} hará del conocimiento del tercero de que se trate, dicha solicitud de rectificación o cancelación, para que proceda a efectuarla también.</Paragraph>
      <Paragraph><strong>{"Derecho de Oposición"}</strong> El Titular tiene en todo momento el derecho a solicitar, siempre que tenga una causa legítima, que {"RADIUS"} deje de tratar sus Datos Personales.</Paragraph>
      <Paragraph><strong>{"Responsable"}</strong> Significa la persona física o moral que decide sobre el tratamiento de los Datos Personales del Titular, en este caso LEE & MILLER, S.C.</Paragraph>
      <Paragraph><strong>{"Encargado"}</strong> Significa la persona física o jurídica que sola o conjuntamente con otras trate Datos Personales por cuenta del Responsable.</Paragraph>
      <Paragraph><strong>{"Titular"}</strong> Significa la persona física titular de los Datos Personales, o autorizada para entregar Datos Personales de un tercero conforme a las leyes aplicables, que entregue dichos Datos Personales al Responsable.</Paragraph>

      <Subtitle>2. CONSENTIMIENTO DEL TITULAR.</Subtitle>
      <Paragraph>Para efectos de lo dispuesto en la LFPDP y en particular en su Artículo 17, el Titular manifiesta (i) que el presente Aviso de Privacidad le ha sido dado a conocer por el Responsable, (ii) haber leído, entendido y acordado los términos expuestos en este Aviso de Privacidad, por lo que otorga su consentimiento respecto del tratamiento de sus Datos Personales para efectos de la LFPDP y demás legislación aplicable. En caso de que los Datos Personales recopilados incluyan Datos Personales sensibles o financieros, mediante la firma del contrato correspondiente, sea en formato impreso, o utilizando medios electrónicos y sus correspondientes procesos para la formación del consentimiento se llevarán a cabo actos que constituyen el consentimiento expreso del titular en términos del segundo párrafo del artículo 8 de la LFPDP y demás legislación aplicable y (iii) que otorga su consentimiento para que LEE & MILLER, S.C o Sus Encargados realicen transferencias de Datos Personales a terceros nacionales o extranjeros, en el entendido de que el tratamiento que dichos terceros den a sus Datos Personales deberá ajustarse a lo establecido en este Aviso de Privacidad.</Paragraph>
      <Paragraph>En caso de que el Titular no se oponga a los términos del presente Aviso de Privacidad dentro los siguientes 30 días en que fue puesto a su disposición, se considerará acordado y consentido su contenido, en términos del tercer párrafo del artículo 8 de la LFPDP. El consentimiento del Titular podrá ser revocado en cualquier momento por éste sin que se le atribuyan efectos retroactivos, en los términos y conforme a los procedimientos establecidos más adelante para ello conforme a este Aviso de Privacidad.</Paragraph>     

      <Subtitle>3. DATOS PERSONALES QUE RECABAMOS.</Subtitle>
      <Paragraph><strong>{"RADIUS"}</strong> puede recolectar datos personales del Titular mediante la entrega directa y/o personal por cualquier medio de contacto entre el Titular y {"RADIUS"} o sus Encargados. También puede recolectar datos personales de manera indirecta a través de fuentes de acceso público y de otras fuentes disponibles en el mercado.</Paragraph>
      <Paragraph>{"RADIUS"} recaba y trata los Datos Personales de identificación, financieros y/o patrimoniales, académicos y laborales así como datos relacionados con preferencias de consumo y navegación al hacer uso de los servicios web que le brindamos</Paragraph>
      <Paragraph>Recolectamos datos al navegar en los sitios y páginas web de LEE & MILLER, S.C. Dentro de las herramientas de captura automática de datos utilizadas por LEE & MILLER, S.C., en su portal web se encuentran las cookies, los Web beacons, y los enlaces en los correos electrónicos.</Paragraph>
      <Paragraph><strong>Uso de Cookies.</strong> – El correcto funcionamiento de los sitios de LEE & MILLER, S.C., y el de sus encargados del tratamiento requieren de la habilitación de {"cookies"} en su navegador de Internet. Las {"cookies"} son pequeños archivos de datos transferidos por el sitio Web al disco duro de su computadora cuando navega por el sitio. Las cookies pueden ser de sesión o permanentes. Las cookies de sesión no se quedan en su computadora después de que usted cierra la sesión de su navegador, mientras que las cookies permanentes se quedan en las computadoras hasta que son eliminan o caducan. Usted puede ajustar las preferencias de su navegador para aceptar o rechazar las cookies. La desactivación de las cookies puede inhabilitar diversas funciones de los sitios web de LEE & MILLER, S.C., o que no se muestren correctamente.</Paragraph>
      <Paragraph><strong>Uso de Web beacons</strong> (también conocidos como etiquetas de Internet, etiquetas de píxel y clear GIFs).- LEE & MILLER, S.C, puede utilizar en su sitios web y en sus correos electrónicos con formato HTML los Web beacons, solos o en combinación con las cookies, para recopilar información sobre el uso de los sitios web y su interacción con el correo electrónico.</Paragraph>
      <Paragraph><strong>Vínculos en los correos electrónicos de LEE & MILLER, S.C.</strong>- Los correos electrónicos que incluyen vínculos que permiten a LEE & MILLER, S.C., saber si usted activó dicho vínculo y visitó la página web de destino, pudiendo esta información ser incluida en su perfil. En caso de que usted prefiera que LEE & MILLER, S.C, no recolecte información sobre su interacción con dichos vínculos, usted puede optar por modificar el formato de las comunicaciones de LEE & MILLER, S.C o puede hacer caso omiso del vínculo y no acceder a su contenido.</Paragraph>
      <Paragraph>Únicamente para el caso de postulantes a empleados y empleados se solicitan datos sensibles relativos a salud y origen.</Paragraph>
      <Paragraph>Los Datos Personales del Titular son recolectados y tratados por el Responsable o sus Encargados con la finalidad de permitirle al Titular, llevar a cabo las siguientes actividades con el Responsable:</Paragraph>

      <Subtitle>4. FINALIDAD DE LOS DATOS PERSONALES.</Subtitle>
      <Paragraph><strong>FINALIDADES PRIMARIAS.</strong> {"RADIUS"} tratará los datos personales del Titular con la finalidad de llevar a cabo las actividades y gestiones enfocadas al cumplimiento de las obligaciones originadas y derivadas de cualquier relación jurídica y comercial que establezcamos con motivo de la prestación de nuestros servicios; facturación; cobranza; crédito; atención a clientes; otorgamiento de garantías; gestión de servicios de valor agregado y contenidos; administración de aplicaciones y sitios Web; Gestión de dominios, cuentas de correo a través del servicio {"RADIUS"} mail, contacto con el cliente; y proporcionar, cambiar o cancelar los servicios que nos solicita el Titular, Realizar estudios sobre los datos demográficos, intereses y comportamiento de sus clientes, consumidores, proveedores, y de aquellos terceros con los que trate, Efectuar estudios de mercado y de consumo a efecto de adquirir y ofrecer productos y servicios personalizados, Elaborar estadísticas internas que indiquen los servicios y productos más apreciados por los diferentes segmentos de sus clientes, consumidores, proveedores y otros usuarios de los servicios que {"RADIUS"} brinda, Verificación de derechos de autor; Gestión de dominios; Gestionar premios; Mantener un registro de las operaciones e información revisada en las distintas secciones de los servicios que {"RADIUS"} brinda y que se recolecta a través de herramientas de captura automática de datos; controlar el acceso físico y lógico a instalaciones, servicios e infraestructura tecnológica; y que el titular pueda:</Paragraph>
      <Paragraph>a) Solicitar, comprar, cambiar, reclamar garantías, devolver productos o cancelar servicios, solicitar una cotización, información o muestras gratuitas de productos y servicios ofrecidos por LEE & MILLER, S.C, sean éstos prestados por nosotros o por conducto de terceros;<br />b) Utilizar los distintos servicios de su portal Web y la descarga de contenidos y formatos;<br />c) Notificar a {"RADIUS"} sobre problemas con sus sitios;<br />d) Participar en chats y/o foros y/o blogs, Participar en trivias, concursos, rifas, juegos y sorteos;<br />e) Compartir sus comentarios o sugerencias sobre los productos y servicios;</Paragraph>
      <Paragraph>Para el caso de los postulantes a empleados y empleados:<br />a) Efectuar el proceso de reclutamiento, selección y contratación de personal;<br />b) Gestión sobre pago de contribuciones, obligaciones, facturas, recibos de honorarios, así como, retribuciones, impuestos y aportaciones del personal</Paragraph>
      <Paragraph><strong>FINALIDADES SECUNDARIAS.</strong> Asimismo, {"RADIUS"} tratará datos personales para las siguientes finalidades:</Paragraph>
      <Paragraph>a) Enviar publicidad impresa o a través de medios electrónicos, incluyendo comunicaciones con fines de mercadotecnia en línea, o telemarketing sobre productos y servicios;<br />b) Ofrecer la plataforma para creación de perfiles personales;<br />c) Realizar encuestas;<br />d) Enviarle al Titular la notificación de ofertas, avisos y/o mensajes promocionales, a menos que el Titular manifieste expresamente su voluntad de no recibir tales ofertas. Ocasionalmente éstas pueden contener información de proveedores de {"RADIUS"} u otros terceros.<br />e) Operar campañas de publicidad y envío de comunicados a clientes;</Paragraph>
      <Paragraph>El titular puede manifestar su negativa para el tratamiento de sus datos personales con relación a las finalidades secundarias conforme lo establece la sección 7 de este aviso.</Paragraph>

      <Subtitle>5. TRANSFERENCIAS DE DATOS.</Subtitle>
      <Paragraph>LEE & MILLER, S.C., requiere compartir sus Datos Personales con proveedores de servicios de administración y gestión de bases de datos; tratamiento automatizado de Datos y su almacenamiento; autenticación y validación de correos electrónicos; contratación de personal y servicios de auditoría.</Paragraph>
      <Paragraph>Habiendo leído, entendido y acordado los términos expuestos en este Aviso de Privacidad, el Titular manifiesta su consentimiento para que {"RADIUS"} realice transferencias de Datos Personales a terceros nacionales o extranjeros, en el entendido de que el tratamiento que dichos terceros den a los Datos Personales del Titular deberá ajustarse a lo establecido en este Aviso de Privacidad.</Paragraph>
      <Paragraph>Para efectos de lo establecido en esta Sección, pero sujeto a lo establecido en el último párrafo de la misma, {"RADIUS"} le informa al Titular que con el objeto de poder entregar productos, servicios y soluciones a sus clientes, consumidores, empleados, proveedores y demás usuarios de sus servicios {"RADIUS"} ha celebrado o celebrará diversos acuerdos comerciales con proveedores de productos y servicios, tanto en territorio nacional como en el extranjero, para que le suministren servicios de: chat, foros, blogs, gestión de dominios, trivias, {"RADIUS"} mail, SONORA; administración y gestión de bases de datos; tratamiento automatizado de Datos Personales y su almacenamiento; call center para atención al cliente; autenticación y validación de correos electrónicos; telemarketing; facturación electrónica; administración de nóminas y beneficios de seguridad social; contratación de personal; servicios de auditoría y otros de naturaleza análoga. La autorización del Titular otorgada conforme a esta Sección faculta a {"RADIUS"} a transmitir Datos Personales del Titular a dichos proveedores, en el entendido de que dichos proveedores están obligados, por virtud del contrato correspondiente, a mantener la confidencialidad de los Datos Personales suministrados por {"RADIUS"} y a observar el presente Aviso de Privacidad. {"RADIUS"} podrán transferir los Datos Personales recolectados del Titular a cualquier otra sociedad del mismo grupo al que pertenece y que operen con los mismos procesos y políticas internas, sea que se encuentren en territorio nacional o en el extranjero para su tratamiento con las mismas finalidades descritas en este Aviso de Privacidad. También podrá transferir sus Datos Personales a otros terceros que le apoyen para cumplir con los contratos o relaciones jurídicas que tenga con el Titular.</Paragraph>
      <Paragraph>Su información personal puede transferirse, almacenarse y procesarse en un país distinto de donde se proporcionó. Sí lo hacemos, transferimos la información de conformidad con las leyes de protección de la información aplicables. Tomamos medidas para proteger la información personal sin importar el país donde se almacena o a donde se transfiere. Tenemos procedimientos y controles oportunos para procurar esta protección.</Paragraph>
      <Paragraph>Nos reservamos el derecho a transmitir sus Datos Personales en caso de vender o traspasar la totalidad o parte de nuestro negocio o activos. En caso de producirse dicha venta o traspaso, haremos todo lo posible para instar al siguiente propietario a utilizar los Datos Personales con arreglo a este Aviso. Si no desea que sus Datos Personales sean procesados tras el traspaso, deberá ponerse en contacto con el nuevo propietario.</Paragraph>
      <Paragraph>No obstante lo dispuesto en esta Sección o en cualquier otro lugar de este Aviso de Privacidad, el Titular reconoce y acepta que el Responsable no requiere de autorización ni su confirmación para realizar transferencias de Datos Personales nacionales o internacionales en los casos previstos en el Artículo 37 de la LFPDP o en cualquier otro caso de excepción previsto por la misma o la demás legislación aplicable.</Paragraph>

      <Subtitle>6. RETENCIÓN Y SEGURIDAD DE LOS DATOS PERSONALES.</Subtitle>
      <Paragraph>El Responsable y/o sus Encargados conservarán los Datos Personales del Titular durante el tiempo que sea necesario para procesar sus solicitudes de información, productos y/o servicios, así como para mantener los registros contables, financieros y de auditoria en términos de la LFPDP y de la legislación mercantil, fiscal y administrativa vigente. Los Datos Personales del Titular recolectados por el Responsable y/o sus Encargados se encontrarán protegidos por medidas de seguridad administrativas, técnicas y físicas adecuadas contra el daño, pérdida, alteración, destrucción o uso, acceso o tratamiento no autorizados, de conformidad con lo dispuesto en la LFPDP y de la regulación administrativa derivada de la misma.</Paragraph>
      <Paragraph><strong>Protección a menores:</strong> LEE & MILLER, S.C., alienta a los padres y/o tutores a tomar un papel activo en las actividades en línea de sus hijos. En caso de que LEE & MILLER, S.C., considere que los Datos Personales han sido proporcionados por un menor en contravención al presente Aviso de Privacidad, LEE & MILLER, S.C., procederá a eliminar tales Datos Personales a la brevedad. Si usted se da cuenta que tales Datos Personales han sido proporcionados por un menor de 18 años, por favor envíe un correo electrónico a la dirección: hola@descubreradius.com</Paragraph>

      <Subtitle>7. DEPARTAMENTO DE DATOS PERSONALES/OFICINA DE PRIVACIDAD; DOMICILIO.</Subtitle>
      <Paragraph>Para cualquier comunicación acerca de nuestro Aviso de Privacidad, por favor contáctenos a hola@descubreradius.com o en:</Paragraph>
      <Paragraph>Av. Junco de La Vega No. Ext. 108-B, Col. Roma, Monterrey, Nuevo León, C.P. 64700</Paragraph>
      <Paragraph>Para efectos de lo dispuesto en la fracción I del Artículo 16 de la LFPDP, el domicilio del Responsable es el establecido en esta Sección 7 del presente Aviso de Privacidad.</Paragraph>

      <Subtitle>8. PROCEDIMIENTO PARA EJERCER LOS DERECHOS.</Subtitle>
      <Paragraph>El Titular tiene, en todo momento, derecho de acceder, rectificar y cancelar sus datos (derechos ARCO), así como de oponerse al tratamiento de los mismos o revocar el consentimiento a las finalidades secundarias que para tal fin haya proporcionado presentando una solicitud con la información y documentación siguiente:</Paragraph>
      <Paragraph>i) Nombre del Titular y domicilio u otro medio para comunicarle la respuesta a su solicitud;</Paragraph>
      <Paragraph>ii) Los documentos que acrediten su identidad (copia simple en formato impreso o electrónico de su credencial de elector, pasaporte o FM-3) o, en su caso, la representación legal del Titular (copia simple en formato impreso o electrónico de la carta poder simple con firma autógrafa del Titular, el mandatario y sus correspondientes identificaciones oficiales – credencial de elector, pasaporte o FM-3);</Paragraph>
      <Paragraph>iii) La descripción clara y precisa de los Datos Personales respecto de los que busca ejercer alguno de los Derechos ARCO, y</Paragraph>
      <Paragraph>iv) Cualquier otro elemento o documento que facilite la localización de los Datos Personales del Titular.</Paragraph>
      <Paragraph>En el caso de las solicitudes de rectificación de Datos Personales, el Titular respectivo deberá también indicar las modificaciones a realizarse y aportar la documentación que sustente su petición.</Paragraph>
      <Paragraph>Para la recepción, registro y atención de las solicitudes para ejercer su derecho de acceso, rectificación, cancelación y oposición a sus Datos Personales, así como para limitar el uso o divulgación de sus datos, y los demás derechos previstos en la LFPDP favor de llenar el formulario correspondiente y contactar al departamento de datos personales:</Paragraph>
      <Paragraph>“RADIUS” le responderá al Titular respectivo la determinación adoptada en un plazo máximo de veinte días hábiles, contados desde la fecha en que se recibió la solicitud de acceso, rectificación, cancelación u oposición a efecto de que, si resulta procedente, se haga efectiva la misma dentro de los quince días siguientes a la fecha en que se le comunica la respuesta al Titular. Tratándose de solicitudes de acceso a Datos Personales, “RADIUS” procederá con su entrega previa acreditación de la identidad del solicitante o de su representante legal, según corresponda. Los plazos antes referidos podrán ser ampliados sólo en términos de la LFPDP.</Paragraph>
      <Paragraph>La entrega de los Datos Personales será gratuita y en el domicilio o a través del medio señalado por el titular en la solicitud correspondiente. En el caso de que el Titular reitere su solicitud de acceso en un periodo menor a doce meses, deberá cubrir los gastos justificados de envío o el costo de reproducción en copias u otros formatos correspondientes equivalentes a 1.5 días de Salario Mínimo Vigente en el Distrito Federal en términos de la LFPDP, a menos que existan modificaciones sustanciales al Aviso de Privacidad que motiven nuevas consultas.</Paragraph>
      <Paragraph>Adicional al procedimiento descrito anteriormente el titular podrá limitar el uso o divulgación de sus datos personales a través de:</Paragraph>
      <Paragraph>I. La inscripción del titular en el Registro Público de Consumidores previsto en la Ley Federal de Protección al Consumidor, en términos del artículo 111 del Reglamento de la Ley;</Paragraph>
      <Paragraph>II. Los medios habilitados por los cuales puede manifestar su negativa a seguir recibiendo comunicados o promociones por parte de “RADIUS”.</Paragraph>

      <Subtitle>9. CAMBIOS AL AVISO DE PRIVACIDAD.</Subtitle>
      <Paragraph>LEE & MILLER, S.C., se reserva el derecho de actualizar periódicamente el presente Aviso para reflejar los cambios de nuestras prácticas de información. Es responsabilidad del Titular revisar periódicamente el contenido del Aviso de Privacidad en el sitio www.descubreradius.com en donde se publicarán los cambios realizados conjuntamente con la fecha de la última actualización. El Responsable, entenderá que de no expresar lo contrario, significa que el Titular ha leído, entendido y acordado los términos ahí expuestos, lo que constituye su consentimiento a los cambios y/o actualizaciones establecidos en dichas actualizaciones respecto al tratamiento de sus Datos Personales para efectos de la LFPDP y demás legislación aplicable.</Paragraph>
      
      <Paragraph>Última actualización: 03-04-2023</Paragraph>
    </div>
  );
};

export default AvisoDePrivacidad;